using System;
using System.Numerics;

namespace ClassLibrary1
{
    public class Zint : IConvertible
    {
        const int max = 1000000; //constant int indicating the maximum generated by random
        private BigInteger r;

        public Zint(int r)
        {
            this.r = r;
        }

        public Zint(BigInteger bigInteger)
        {
            this.r = bigInteger;
        }

        public static Zint RandomPositive()
        {
            Random random = new Random();
            int r = random.Next();
            return new Zint(r);
        }

        public static Zint Random()
        {
            Random random = new Random();
            if (random.Next(2) == 0)
            {
                return RandomPositive();
            }
            else
            {
                return RandomPositive().Negate();
            }
        }

        public Zint Negate()
        {
            return new Zint(this.r * -1);
        }
    }
}